### ISSUE TITLE
Occasional false comps

### ISSUE THREAD

**Issue by kneasle** [kneasle/ringing#72]
Sometimes Monument generates a false composition, for example for this input:
```toml
length = "Peal"
methods = [
    "Cambridge Surprise Major",
    "Yorkshire Surprise Major",
    "Superlative Surprise Major",
    "Bristol Surprise Major",
    { title = "Cornwall Surprise Major", shorthand = "W" },
    { title = "Lessness Surprise Major", shorthand = "E" },
    "London Surprise Major",
]
music_file = "music-8.toml"
base_calls = "near"
bob_weight = -4
single_weight = -4
num_comps = 20
part_head = "14236578"
course_heads = ["*78", "*7856"]
method_count = { min = 500, max = 900 }
```
we get the following false comp: `B[sH]BEL[B]W[V]EEW[sM]B[sM]WEW[sV]S[B]SC[H]YCS[sM]YYLC[B]SY[sH]LC[sW]B`
